### ISSUE TITLE
Discussion on package maintainance

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#11]
Thought I would make an issue chain since it is easier to follow.

So first thing first is to get all ROCm related packages in this repo
- [x] @neeshy 
- [x] @farnoy 
- [x] @naetherm 
- [x] @ranisalt
- [x] @rigred

Once we have all the packages in this repo, it would be nice if we can get some CI going with this and automatic syncing with the AUR.

- [ ] CI
- [ ] automatic syncing to the AUR

Having binary packages for these PKGBUILDs seems like a really good idea as well, especially since some of them take forever, looking at you llvm. We can talk to the [arch4edu](https://github.com/arch4edu/arch4edu) folks and request binary packages for our repo. Associated request: https://github.com/arch4edu/arch4edu/issues/60

- [x] binary packages

Once we get a significant number of binary packages, let's also try to upstream ArchLinux installation instructions for using the binary repo and these PKGBUILDs. Upstream PR to add instructions on installing ROCm on Arch: https://github.com/RadeonOpenCompute/ROCm_Documentation/pull/73
Note: Since AMD does not officially support Arch Linux, they cannot add the instructions to their repo however, they did create a community FAQ [here](https://community.amd.com/message/2981124) based on the above PR. Checking this off.

- [x] add upstream instructions

With regards to documentation, I think it would be nice if someone can flesh out the ArchWiki section for ROCm [here](https://wiki.archlinux.org/index.php/GPGPU#ROCm).
For a more concrete documentation plan, see: https://github.com/rocm-arch/rocm-arch/issues/204

- [ ] flesh out ROCm entry on the ArchWiki

We also should get all the packages under one maintainer, so as to prevent each other from pushing to the AUR outside of this repo. (Maybe this step should be done after we automate the syncing.)

- [x] Put packages under one maintainer

After the builds work we should also get the test suites working, to actually confirm the working status of our packages. This also might help us pinpoint other errors like runtime performance.

- [ ] Add `check()` functions in PKGBUILDs

**Comment by ranisalt** [comment]
I would separate the packages into repositories instead of one huge monorepo. Not only it makes it much easier to bisect and fix bugs, large repos are slow to clone and commit.

**Comment by ranisalt** [comment]
Also, I propose a workflow:

We should have a `master` branch that is in sync with AUR. We also have a `dev` branch that contains the latest improvements, but not necessarily updated .SRCINFO and pkgsums. Whenever a new version is released, the differences since the last `master` commit should be **squashed**, together with a version bump and updated .SRCINFO and pkgsums, merged into master and then pushed to the AUR.

That way, we don't need to manage separate repository structures for AUR packages and Github repositories, while keeping pace should an improvement to the build script that is not strictly necessary not getting delayed or forgotten.

**Comment by acxz** [comment]
> I would separate the packages into repositories instead of one huge monorepo. Not only it makes it much easier to bisect and fix bugs, large repos are slow to clone and commit.

Agreed, but the amount of packages we are dealing with are rather small.

**Comment by acxz** [comment]
> Also, I propose a workflow:
> 
> We should have a `master` branch that is in sync with AUR. We also have a `dev` branch that contains the latest improvements, but not necessarily updated .SRCINFO and pkgsums. Whenever a new version is released, the differences since the last `master` commit should be **squashed**, together with a version bump and updated .SRCINFO and pkgsums, merged into master and then pushed to the AUR.
> 
> That way, we don't need to manage separate repository structures for AUR packages and Github repositories, while keeping pace should an improvement to the build script that is not strictly necessary not getting delayed or forgotten.

Are you familiar with [`aurpublish`](https://github.com/eli-schwartz/aurpublish/)? We are currently using git subtrees for our pipeline.

**Comment by acxz** [comment]
@ranisalt it would be much appreciated if add me, neeshy, or naetherm as the package co maintainers to your rocm related packages.

**Comment by ranisalt** [comment]
> Are you familiar with [`aurpublish`](https://github.com/eli-schwartz/aurpublish/)?

No, I will read about it.

> @ranisalt it would be much appreciated if add me, neeshy, or naetherm as the package co maintainers to your rocm related packages.

Sorry for the delay! Done that.

**Comment by rigred** [comment]
Ok

My rocm-smi package is located here
https://github.com/rigred/ROC-smi_arch

How do you want it included? Shall I make a pull request?

**Comment by acxz** [comment]
sweet, I took care of it with an `aurpublish -p rocm-smi` and pushed to master: 4b767fa

**Comment by farnoy** [comment]
Thanks for pushing this forward, you've made a lot of progress so far!

 I have two questions about aurpublish:
* Does it filter the history of the monorepo in some way, or will all commits here get pushed to AUR (just some of them empty if they do not modify that subtree/package)?
* Can we set it up so that only the CI would run `aurpublish` and push to AUR? If this CI step only happened on master or some special branch, it should give everyone freedom to collaborate on branches and merge to the publishing branch. If this setup is possible, there should be no reason for any maintainer to publish anything without going through this monorepo.

**Comment by acxz** [comment]
Thanks!

So `aurpublish` is actually just a wrapper for `git subtrees`.

Any commit you make that changes anything under `<package_name>/` gets registered as `<package_name>: <commit_message_for_monorepo>` for that specific package. If the commit to the monorepo does not change that folder, nothing will get pushed. All commits here should be treated as commits that will be made on top of the AUR repo of the package, `aurpublish <package_name>` will perform a push of commits associated with this repo's `<package_name>` subtree to the AUR repo of `<package_name>`. Note we can squash our commits.

I would prefer if the CI did the building before pushing to the AUR. `aurpublish` will only work for you if you are a maintainer/co-maintainer for the AUR package.

**Comment by farnoy** [comment]
Got it. Would it be enough to agree, as maintainers, never to run `aurpublish` on a revision that is not pushed to the master branch of this monorepo? I think that if we followed this rule, we'd never see errors from conflicting pushes, which I imagine could get a bit hairy with so many subtrees.

**Comment by acxz** [comment]
I think we should have only one maintainer anyway, so that we can control the sync to AUR easily, but yes aurpublish should only be used from the master branch.

**Comment by acxz** [comment]
I was also thinking it might be a p good idea to have a chatroom on this project.

**Comment by acxz** [comment]
Created an upstream PR to add instructions on installing ROCm on Arch: https://github.com/RadeonOpenCompute/ROCm/pull/1055

**Comment by ranisalt** [comment]
I managed to build llvm-roc with Github Actions, cache included and all so rebuilds take only a couple of minutes instead of the regular two hours for a build from scratch:

https://github.com/ranisalt/llvm-roc-actions

I don't know how to use it here, but there's a workflow to build an Arch Linux package, I hope it can be useful here.

**Comment by acxz** [comment]
Whoa thats great! Yeah let's try to add this workflow to this repo.

**Comment by acxz** [comment]
@naetherm it seems like you have made several commits but have not synced them to the AUR. Can you ahead and do that like so: `aurpublish <package_name>`? It is important to keep close to the AUR when committing or to make an issue if said committer does not have privileges to the AUR package.

**Comment by ranisalt** [comment]
Also it seems that some version bumps reverted previous commits. Please take care with pulling before changing anything to avoid these issues.

**Comment by naetherm** [comment]
> @naetherm it seems like you have made several commits but have not synced them to the AUR. Can you ahead and do that like so: `aurpublish <package_name>`? It is important to keep close to the AUR when committing or to make an issue if said committer does not have privileges to the AUR package.

Of course, I wanted to update other libraries as well before running an `aurpublish` but I could also do that in sync with pushing.

**Comment by aviallon** [comment]
You are the bests. Thank you.

**Comment by acxz** [comment]
@naetherm @rigred @ranisalt is it possible for you guys to hand over complete maintainership (instead of just co-maintainership) to me?

I would like to add more people (which I cannot soley on co-maintainership) and based on the activity that you guys have in the previous months, I believe it is proper if you can hand the properly hand the packages over.

Thank you for understanding.

**Comment by ranisalt** [comment]
@acxz 

Done with:
- rocrand
- rocsolver
- rocminfo
- rocm-opencl-runtime
- rocm-device-libs
- rocfft
- miopengemm
- llvm-amdgpu
- comgr
- rocm-cmake-git

I just kindly ask that you keep the contributor tag. Unfortunately, I don't have AMD hardware anymore :( once 6800 XTs are available to buy and run ROCm I may come back to assist.

**Comment by acxz** [comment]
We will always be grateful for your work and can't wait once your back. We definitely will keep all contributor tags :)

Thanks for handing over maintainership!

**Comment by acxz** [comment]
@naetherm @rigred friendly ping asking if you can hand over AUR maintainership.

**Comment by acxz** [comment]
Thanks @naetherm!

@rigred @farnoy friendly ping asking if you can hand over AUR maintainership.

**Comment by naetherm** [comment]
You're welcome and sorry for the later answer, I had very busy times ...

**Comment by acxz** [comment]
I'm gonna go ahead and transfer the AUR packages to @tpkessler as I will also be toning down my activity.

**Comment by tpkessler** [comment]
Thank you @acxz for the smooth transition. I've already used my new power to fix the `miopen-*` packages.

**Comment by farnoy** [comment]
Sorry about paralyzing your workflow @tpkessler, I disowned these 10 packages you requested:

```
hipblas
hipcub
hipsparse
rccl
rocalution
rocblas
rocm-cmake
rocprim
rocsparse
rocthrust
```

**Comment by ranisalt** [comment]
You transferred them all to me :facepalm: I transferred them again to @tpkessler

Next time someone transfers packages, please update the maintainer list, the first name will be the recipient.

**Comment by rigred** [comment]
Been a very busy few months for me.
Hadn't had time to even look at Github much.
But am back now.

Just transfered packages to @tpkessler

**Comment by tpkessler** [comment]
Thank you @farnoy @ranisalt and @rigred  for transferring the packages to me. I'm now in full control of the ROCm stack for Arch Linux.

**Comment by acxz** [comment]
I think with that we can finally close this issue!

**Comment by ranisalt** [comment]
@tpkessler :clap: treat it well :laughing:
