### ISSUE TITLE
Add everybody to each package's list of co-maintainers

### ISSUE THREAD

**Issue by neeshy** [rocm-arch/rocm-arch#27]
This includes: naetherm, neeshy, rsa

So far we have:

- [x] aomp
- [x] atmi
- [x] clang-ocl
- [ ] comgr
- [x] hcc
- [x] hcc-git
- [x] hip
- [x] hipblas
- [x] hip-clang
- [x] hipcub
- [x] hip-git
- [x] hip-hcc
- [x] hip-nvcc
- [x] hipsparse
- [ ] hsa-amd-aqlprofile
- [ ] hsa-ext-rocr
- [x] hsa-rocr
- [ ] hsa-rocr-git
- [ ] hsakmt-roct
- [ ] hsakmt-roct-git
- [ ] llvm-amdgpu
- [x] llvm-roc
- [x] migraphx
- [x] miopen
- [x] miopengemm
- [x] mivisionx
- [x] rccl
- [x] rocalution
- [x] rocblas
- [x] rocfft
- [x] rock-dkms
- [x] rock-dkms-git
- [x] rocm-bandwidth-test
- [x] rocm-dev
- [x] rocm-device-libs
- [x] rocm-dkms
- [x] rocm-clang-ocl
- [x] rocm-cmake
- [x] rocm-cmake-git
- [x] rocm-comgr
- [x] rocm-libs
- [x] rocm-opencl-runtime
- [x] rocm-smi
- [x] rocm-smi-lib
- [x] rocm-utils
- [x] rocm-validation-suite
- [x] rocminfo
- [x] rocprim
- [x] rocprofiler
- [x] rocr-debug-agent
- [x] rocrand
- [x] rocr-runtime-git
- [x] rocsparse
- [x] rocthrust
- [x] roctracer

**Comment by acxz** [comment]
@neeshy you can keep me off the list. I believe the less number of people as co-maintainers the better. There is no reason for 5 people to be in charge of syncing AUR packages now that we have this github repo, where we can contribute and create PRs freely, unlike the AUR.

**Comment by naetherm** [comment]
Updated the list according to the maintainer list and @acxz comment.

Regarding the ```hipsycl-*-git```:
Should those really belong of this repository though ```hipsycl-*-git``` is not part of the ROCm infrastructure?

**Comment by acxz** [comment]
That’s a good question actually, I think we should remove the hipsycl packages from this repo. I would like to take maintainership of them.

**Comment by rigred** [comment]
As of right now rocm-utils depends on rocm-clang-ocl which is outdated of repo as @whoisroot hasn't yet submitted code or not been merged in here. Lots of packages depend on that.

Should we just go ahead and manually merge it?

**Comment by acxz** [comment]
We will pull it in once once of the maintainers of this repo has AUR push access to it.

**Comment by rigred** [comment]
Just got ownership of rocm-clang-ocl and assigned the team as maintainers.
I would push the changes but it's very late for me and I don't want to push changes sleepy.

**Comment by acxz** [comment]
Sweet thanks just took care of it!

**Comment by acxz** [comment]
closing this issue since no one is really keeping up with it and I think we should only have 1 AUR maintainer anyways responsible for the syncing.
