### ISSUE TITLE
Some compilation errors in clean chroot

### ISSUE THREAD

**Issue by petronny** [rocm-arch/rocm-arch#68]
I'll post them one by one here.

- [x] [hip-hcc](https://github.com/rocm-arch/rocm-arch/issues/68#issuecomment-604272120) [updated on 2020-04-30]
- [x] [rocm-clang-ocl](https://github.com/rocm-arch/rocm-arch/issues/68#issuecomment-604274108)
- [x] [rocr-debug-agent](https://github.com/rocm-arch/rocm-arch/issues/68#issuecomment-604274480)
- [x] [rocm-opencl-runtime](https://github.com/rocm-arch/rocm-arch/issues/68#issuecomment-604275518)

All of them are built in clean chroot.

**Comment by petronny** [comment]
About hip-hcc

I get errors like
```
: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-10: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-10: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-10: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-10: warning: -Xlinker --enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/src/hip_error.cpp:23:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hip_runtime.h:56:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/hip_runtime.h:57:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hip_runtime_api.h:342:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/hip_runtime_api.h:42:
/build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/host_defines.h:47:22: error: invalid token at start of a preprocessor expression
#if __hcc_workweek__ >= 17481
                     ^
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/src/hip_module.cpp:23:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hip_runtime.h:56:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/hip_runtime.h:57:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hip_runtime_api.h:342:
In file included from /build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/hip_runtime_api.h:42:
/build/hip-hcc/src/HIP-roc-3.1.0/include/hip/hcc_detail/host_defines.h:47:22: error: invalid token at start of a preprocessor expression
#if __hcc_workweek__ >= 17481
```
This is the first time that `error:` appears.

**Comment by petronny** [comment]
About rocm-clang-ocl
```
==> Starting build()...
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find ROCM (missing: ROCM_DIR)
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    ROCMSetupVersion


CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    ROCMCreatePackage


CMake Error at CMakeLists.txt:13 (rocm_setup_version):
  Unknown CMake command "rocm_setup_version".


-- Configuring incomplete, errors occurred!
See also "/build/rocm-clang-ocl/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```

**Comment by petronny** [comment]
About rocr-debug-agent
```
==> Starting build()...
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:156 (message):
  Lightning Compiler can't be found


-- Configuring incomplete, errors occurred!
See also "/build/rocr-debug-agent/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```

**Comment by petronny** [comment]
About rocm-opencl-runtime
```
make[2]: Leaving directory '/build/rocm-opencl-runtime/src/rocm-device-libs/build'
[100%] Built target ocml_lib
[100%] Generating opencl.amdgcn.bc
make[2]: Leaving directory '/build/rocm-opencl-runtime/src/rocm-device-libs/build'
[100%] Built target opencl_lib
make[1]: Leaving directory '/build/rocm-opencl-runtime/src/rocm-device-libs/build'
  -> Building OpenCL runtime...
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find ROCT (missing: FIND_ROCT_INCLUDES FIND_ROCT_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindROCT.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/rocm-opencl-runtime/src/rocm-opencl-runtime/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```

**Comment by acxz** [comment]
Thx for the build logs! We will try to address as quickly as we can. These packages do install on my system (I haven't tried with a clean chroot), so it should be simple to iron these issues out.

**Comment by ranisalt** [comment]
For hip: you are missing python, install it.
For rocm-clang-ocl: install rocm-cmake and add `-DROCM_DIR=/opt/rocm/share/rocm/cmake` to the cmake call.
For rocm-opencl-runtime: install roct-thunk-interface.

**Comment by petronny** [comment]
> For hip: you are missing python, install it.
> For rocm-clang-ocl: install rocm-cmake and add `-DROCM_DIR=/opt/rocm/share/rocm/cmake` to the cmake call.
> For rocm-opencl-runtime: install roct-thunk-interface.

Please add them to the corresponding PKGBUILD(s).

**Comment by ranisalt** [comment]
Yes, I am working on updating these (at least `rocm-opencl-runtime`) :D thanks for the feedback.

**Comment by petronny** [comment]
`rocm-opencl-runtime` is fixed but `hip-hcc` still fails with python installed.

**Comment by kozross** [comment]
Worth noting that ``rocm-opencl-runtime`` had a [change in dependencies recently][1].

[1]: https://github.com/rocm-arch/rocm-arch/issues/75#issuecomment-605378385

**Comment by acxz** [comment]
@petronny `rocm-clang-ocl` should be fixed with `3.1.0-2`

**Comment by petronny** [comment]
Yeah, `rocm-clang-ocl` is fixed now.

**Comment by petronny** [comment]
`rocr-debug-agent` changed its dependency from `rocr-runtime` to `hsa-rocr`.
But it's still raising the same error.

**Comment by petronny** [comment]
About `rocr-debug-agent`,
it seems that the `Lightning Compiler` here is `/opt/rocm/opencl/bin/x86_64/clang`.
Which package does it belong to?

**Comment by ranisalt** [comment]
`llvm-roc` or `rocm-clang-ocl` will have it, but the former installs to `/opt/rocm/bin/clang`.

**Comment by acxz** [comment]
Sorry for getting back p late, end of the semester is always rough. `rocr-debug-agent-3.3.0-2` should resolve the Lightning Compiler issue.

**Comment by acxz** [comment]
I can't seem to figure the hip-hcc error. Since you last upgraded the hip package, can you tell us how you got it to work @naetherm ? Here is the error I'm getting along with others: https://github.com/rocm-arch/rocm-arch/issues/68#issuecomment-604272120
I tried finding something on the upstream issue page but couldn't. We might have to submit an upstream issue for this. I'll wait for a response from @naetherm on this before submitting one.

**Comment by petronny** [comment]
`rocr-debug-agent` is fixed now.
However,  the latest version of `rocm-comgr` fails to build with the following error:

```
[ 85%] Linking C executable include_subdirectory_test
[ 86%] Linking C executable disasm_instr_test
/usr/bin/ld: warning: libLLVM-11git.so, needed by ../libamd_comgr.so.1.6, not found (try using -rpath or -rpath-link)
[ 87%] Linking C executable disasm_options_test
/usr/bin/ld: warning: libLLVM-11git.so, needed by ../libamd_comgr.so.1.6, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libLLVM-11git.so, needed by ../libamd_comgr.so.1.6, not found (try using -rpath or -rpath-link)
[ 88%] Linking C executable symbols_iterate_test
[ 89%] Linking C executable isa_name_parsing_test
/usr/bin/ld: warning: libLLVM-11git.so, needed by ../libamd_comgr.so.1.6, not found (try using -rpath or -rpath-link)
[ 90%] Linking C executable disasm_llvm_so_test
[ 91%] Linking C executable compile_test
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::APInt::getLoBits(unsigned int) const@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::StructType::get(llvm::LLVMContext&, llvm::ArrayRef<llvm::Type*>, bool)@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::cl::PrintOptionValues()@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::GCOVProfilerPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::DIBuilder::DIBuilder(llvm::Module&, bool, llvm::DICompileUnit*)@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::GlobalIFunc::create(llvm::Type*, unsigned int, llvm::GlobalValue::LinkageTypes, llvm::Twine const&, llvm::Constant*, llvm::Module*)@LLVM_11'
/usr/bin/ld: ../libamd_comgr.so.1.6: undefined reference to `llvm::cl::parser<unsigned long long>::printOptionDiff(llvm::cl::Option const&, unsigned long long, llvm::cl::OptionValue<unsigned long long>, unsigned long) const@LLVM_11'
```

**Comment by ranisalt** [comment]
@petronny check #115

**Comment by lordheavy** [comment]
@petronny still broken here (in a clean chroot ofc)

**Comment by ranisalt** [comment]
@petronny #115 was merged and publish, please try updating rocm-comgr.

**Comment by lordheavy** [comment]
@ranisalt fixed rocm-comgr compilation in a clean chrrot by adding "-DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath-link,/opt/rocm/lib" \"

See https://github.com/rocm-arch/rocm-arch/issues/113#issuecomment-615929812

**Comment by petronny** [comment]
I just check the build log and `rocm-comgr 3.3.0-3` fails at 94%. (The build log in the previous comment has been updated.)

**Comment by ranisalt** [comment]
Is the rest of the stack updated? Namely, it seems to be an issue with either rocm-comgr using dirty caches or llvm-roc.

**Comment by petronny** [comment]
I've arranged rebuilds of all the dependencies of `rocm-comgr` (`llvm-roc`, `rocm-cmake` and `rocm-device-libs`). We can get the result tomorrow.

**Comment by petronny** [comment]
I'm sure all dependencies are rebuilt.
But `rocm-comgr` still fails at 91% (build log updated).

**Comment by acxz** [comment]
We are now following upstream naming conventions and dropping rocm-comgr with comgr. I was able to build comgr in a clean root.

**Comment by petronny** [comment]
Ok, I'm replacing `rocm-comgr` with `comgr` now.

But `hip-hcc` still fails after `rocm-comgr` is replaced by `comgr`. (Build log updated.)

**Comment by acxz** [comment]
@petronny I think we got `hip-hcc` with `hip-hcc-3.3.0-3` building fine, can you confirm? We also updated `hcc`.

**Comment by petronny** [comment]
It's still not working...
I've updated the build log.
PS. Here is the full build command.
```
['extra-x86_64-build', '--', '-I', PosixPath('/home/calil/arch4edu/arch4edu/llvm-amdgpu/llvm-amdgpu-3.3.0-2-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/hsakmt-roct/hsakmt-roct-3.3.0-1-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/comgr/comgr-3.3.0-2-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/hsa-rocr/hsa-rocr-3.3.0-5-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/hcc/hcc-3.3.0-2-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/rocm-cmake/rocm-cmake-3.3.0-2-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/llvm-roc/llvm-roc-3.3.0-3-x86_64.pkg.tar.zst'), '-I', PosixPath('/home/calil/arch4edu/arch4edu/rocm-device-libs/rocm-device-libs-3.3.0-4-any.pkg.tar.zst'), '-d', '/home/calil/.cargo:/build/.cargo', '-d', '/home/calil/go:/build/go', '-d', '/home/calil/.cache/archbuild-bind-cache:/build/.cache', '-d', '/home/calil/.cache/go-build:/build/.cache/go-build', '-d', '/home/calil/.cache/pip:/build/.cache/pip', '--', '--noprogressbar']
```

**Comment by petronny** [comment]
About this error:
```
#if __hcc_workweek__ >= 17481
```
I think there should be a file that contains a line like:
```
#define __hcc_workweek__ 17481
```
But it's not imported in the build system.

**Comment by acxz** [comment]
@petronny sorry about that it seems like some hip-hcc deps were not updated on the AUR. This has been done and along with the updated deps, `hip-hcc` has also been updated to `hip-hcc-3.3.0-4`

**Comment by marciosr** [comment]
I have similar issue trying to build hip-hcc on a clean chroot.
It isn't in a normal build so i tried in an chroot.
[build-hip-hcc.log](https://github.com/rocm-arch/rocm-arch/files/4564621/build-hip-hcc.log)

**Comment by petronny** [comment]
Still, the same error with `hip-hcc-3.3.0-4`

**Comment by petronny** [comment]
Hi, I did a little research about `hip-hcc` and here is what I find:

About `__hcc_workweek__`, there is a discription about it in [CONTRIBUTING.md](https://github.com/ROCm-Developer-Tools/HIP/blob/master/CONTRIBUTING.md#testing-hcc-version) in the repo [ROCm-Developer-Tools/HIP](https://github.com/ROCm-Developer-Tools/HIP). And it says
> hcc binary can print the work-week to stdout
```
> /opt/rocm/hcc/bin/hcc -v
HCC clang version 3.5.0  (based on HCC 0.8.16014-81f8a3f-f155163-5a1009a LLVM 3.5.0svn)
```
The `16014` here is the `__hcc_workweek__` version.
However, with `hcc` installed, I get
```
$ /opt/rocm/hcc/bin/hcc -v
HCC clang version 10.0.0  (based on HCC 3.1.-- )
```
No `__hcc_workweek__` version here.
I think this is because we are using
```
source=("https://github.com/ROCm-Developer-Tools/HIP/archive/rocm-$pkgver.tar.gz")
```
not
```
source=("git+https://github.com/ROCm-Developer-Tools/HIP#tag=rocm-$pkgver")
```
in its `PKGBUILD`. But I haven't tested it yet.

For now, I'm just by-passing the `__hcc_workweek__` things by replacing them with `99999` (it will ever be greater than 99536).
```
$ sed -i 's/__hcc_workweek__/99999/g' $(grep __hcc_workweek__ . -rIl)
```
All errors about `__hcc_workweek__` is gone now.
But I'm still getting the following errors:
```
/build/hip-hcc/src/HIP-rocm-3.3.0/src/hip_context.cpp:101:44: error: expected expression
        *runtimeVersion = HIP_VERSION_PATCH;
```
`HIP_VERSION_PATCH` is not generated by `cmake`.

By reading `CMakeList.txt`, `HIP_VERSION_PATCH` should be something generated by `git tag`.

So I changed the `source` array in `PKGBUILD` from
```
source=("https://github.com/ROCm-Developer-Tools/HIP/archive/rocm-$pkgver.tar.gz")
```
to
```
source=("git+https://github.com/ROCm-Developer-Tools/HIP#tag=rocm-$pkgver")
```
And then I can build `hip-hcc` in a clean chroot.

So we have 2 options now:
1. Changing the source of these packages from tarball to git repo.
1. Adjusting code to fit the situations that we are building from a tarball.

**Comment by acxz** [comment]
Wow thanks for looking into this, @petronny! 
hmmm, that is very weird for sure. I think for now it would be cleaner to just change the sources to use the git repo instead of adjusting the code.

In the back of my mind I feel like we may be just missing a `git` or some other dependency somewhere in the packages. Many people such as @s-bernard have been able to compile hip-hcc without this workaround, even I was able to at one point. In any case if it works, it is better than it not working.

Would you be willing to submit a PR with these changes?

**Comment by petronny** [comment]
> In the back of my mind I feel like we may be just missing a git or some other dependency somewhere in the packages. 

I just tested the case that only adding `git` to `makedepends` but still using the tarball.
It does build in this case.

> Would you be willing to submit a PR with these changes?

OK. Sure.

**Comment by acxz** [comment]
Whoa that was just a hunch, glad it worked!!!

**Comment by acxz** [comment]
Do you think if git is added to `hcc` than the __hcc_workweek__ 99999 patch isn't needed either?

**Comment by acxz** [comment]
hmm maybe not, let's not worry about it right now.

**Comment by petronny** [comment]
Only adding git to `hcc`'s makedepends may not solve the problem.

The key issue is how `__hcc_workweek__` is generated.
Basically `__hcc_workweek__` is another form of the date of the project.
We can get the date by a git commit if we are in a git project.
But tarball doesn't have the commits.
Therefore we can't get the date.

We may also need to change `hcc`'s source to git repo.

**Comment by acxz** [comment]
I see, then yeah I think the solution you came up with the best one. 
Just pushed hip-hcc to the AUR.
Thank you once again!

**Comment by acxz** [comment]
@petronny can we go ahead and close this issue?

**Comment by petronny** [comment]
Yeah

**Comment by acxz** [comment]
Thx for looking into this deeper, I see yeah if we can get a clean build with `git` instead of the patch that would be great.
